import React, { createContext, useState, useEffect } from 'react';

export const LanguageContext = createContext();

export const LanguageProvider = ({ children }) => {
  const [language, setLanguage] = useState(() => {
    return localStorage.getItem('app_language') || 'en';
  });

  useEffect(() => {
    localStorage.setItem('app_language', language);
  }, [language]);

  const toggleLanguage = (lang) => {
    setLanguage(lang);
  };

  const t = (key) => {
    const translations = {
      en: {
        dashboard: "Dashboard",
        my_profile: "My Profile",
        open_account: "Open New Account",
        kyc_verification: "KYC Verification",
        balance_check: "Check Balance",
        transaction_history: "Transaction History",
        account_details: "Account Details",
        help_support: "Help & Support",
        settings: "Settings",
        logout: "LogOut",
        account_number: "Account Number",
        account_holder: "Account Holder",
        account_type: "Account Type",
        select_account_type: "Select Account Type",
        saving_account: "Saving Account",
        current_account: "Current Account",
        check_balance_btn: "Check Balance",
        checking_btn: "Checking...",
        download_statement: "Download Statement PDF",
        profile: "Profile",
        security: "Security",
        preferences: "Preferences",
        language: "Language",
        english: "English",
        marathi: "Marathi (मराठी)",
        money_transfer: "Money Transfer",
        beneficiary_details: "Beneficiary Details",
        acc_holder_name: "Account Holder Name",
        confirm_acc_number: "Confirm Account Number",
        ifsc_code: "IFSC Code",
        ifsc_note: "Ensure the IFSC code is exactly 11 characters.",
        payment_details: "Payment Details",
        amount_to_transfer: "Amount to Transfer",
        remarks_optional: "Remarks (Optional)",
        what_is_this_for: "What is this for?",
        clear_details: "Clear Details",
        transfer_securely: "Transfer Securely",
        processing: "Processing...",
        transfer_success: "Transfer Successful",
        transfer_success_msg: "Your funds have been securely transferred to the beneficiary.",
        secure_footer: "Transfers are processed instantly and are secured by 256-bit encryption.",
        submit_kyc: "Submit New KYC",
        step_1: "Step 1 of 3 — Personal Information",
        step_2: "Step 2 of 3 — Document Details",
        step_3: "Step 3 of 3 — OTP Verification",
        personal: "Personal",
        documents: "Documents",
        otp: "OTP",
        full_name: "Full Name",
        email: "Email",
        phone: "Phone",
        dob: "Date of Birth",
        address: "Address",
        next: "Next",
        aadhaar_number: "Aadhaar Number",
        pan_number: "PAN Number",
        aadhaar_doc: "Aadhaar Document",
        pan_doc: "PAN Document",
        upload_aadhaar: "Upload Aadhaar PDF or Image",
        upload_pan: "Upload PAN PDF or Image",
        upload_limit: "PDF, JPG, PNG — Max 5MB",
        kyc_pending_note: "After submission, KYC will be Pending until reviewed by admin.",
        back: "Back",
        sending_otp: "Sending OTP...",
        kyc_success: "KYC Successfully Submitted!",
        kyc_success_msg: "Your KYC is now Pending review. Admin will verify your documents shortly.",
        enter_otp: "Enter OTP",
        otp_placeholder: "6-digit OTP",
        otp_expiry: "OTP expires in",
        resend_otp: "Resend OTP",
        submitting: "Submitting...",
        submit_kyc_btn: "Submit KYC",
        secure_portal: "Secure Banking Registration Portal",
        personal_details: "Personal Details",
        bank_holder_name: "Full Name (Bank Holder)",
        father_name: "Father Name",
        gender: "Gender",
        select_gender: "Select Gender",
        male: "Male",
        female: "Female",
        other: "Other",
        contact_details: "Contact Details",
        residential_address: "Residential Address",
        preferred_branch: "Preferred Branch",
        purpose_of_opening: "Purpose of Opening Account",
        nominee_details: "Nominee Details",
        nominee_name: "Nominee Name",
        nominee_relation: "Relation with Nominee",
        doc_upload: "Document Upload",
        passport_photo: "Passport Photo",
        clear_face_photo: "Clear face photo",
        front_aadhaar: "Front side of Aadhaar",
        clear_pan_img: "Clear PAN card image",
        click_to_upload: "Click to upload",
        terms_agree: "I confirm that all the information provided is accurate and correct.",
        add_signature: "Add Signature",
        pending_approval: "Pending Approval",
        submission_received: "Submission received. Admin review in progress.",
        applicant: "Applicant",
        okay_understood: "Okay, Understood",
        profile_update_success: "Profile updated successfully ✅",
        error_occurred: "An error occurred ❌",
        acc_no: "Account No",
        acc_not_opened: "Account: Not opened yet",
        save: "Save",
        edit: "Edit",
        saving: "Saving...",
        branch: "Branch",
        ifsc: "IFSC Code",
        placeholder_address: "Enter your address...",
        address_not_added: "Address not added yet — click Edit to add",
        acc_not_opened_msg: "Bank account not opened yet. Please open a new account to start your services.",
        create_acc_btn: "CREATE ACCOUNT",
        secure_smart_banking: "Secure · Smart · Banking",
        loading_acc_details: "Loading account details...",
        official_record: "OFFICIAL RECORD",
        download_statement_btn: "Download Statement",
        no_acc_linked: "No bank account linked to your profile.",
        open_new_acc_btn: "+ Open New Account",
        active: "Active",
        bank_name: "Bank",
        payzen_bank: "PayZen Bank",
        personal_info: "Personal Information",
        contact_info: "Contact Information",
        kyc_info: "KYC Information",
        nominee_info: "Nominee Information",
        kyc_verified: "KYC Verified",
        registered_address: "Registered Address",
        disclaimer_mask: "Sensitive information such as Aadhaar and PAN numbers are partially masked for your security. For full details, visit your nearest PayZen Bank branch with valid ID proof.",
        copied: "Copied",
        copy: "Copy",
        acc_info: "Account Information",
        notifications: "Notifications",
        manage_account_pref: "Manage your account preferences",
        edit_profile: "Edit Profile",
        update_profile_info: "Update your profile information",
        profile_info: "Profile Information",
        edit_profile_details: "Edit your profile details",
        data_encrypted_secure: "Your data is encrypted and secure.",
        cancel: "Cancel",
        saved: "Saved",
        save_changes: "Save Changes",
        security_settings: "Security Settings",
        manage_acc_protection: "Manage your account protection",
        change_password: "Change Password",
        update_pwd_regularly: "Update your login password regularly",
        change: "Change",
        current_pwd: "Current Password",
        new_pwd: "New Password",
        confirm_pwd: "Confirm Password",
        updating: "Updating...",
        update_pwd_btn: "Update Password",
        recent_activity: "Recent Activity",
        success_login: "Success Login",
        failed_login: "Failed Login",
        no_recent_activity: "No recent activity found.",
        notif_pref: "Notification Preferences",
        control_alerts: "Control what alerts you receive",
        save_pref_btn: "Save Preferences",
        manage_lang_pref: "Manage app language and other preferences",
        choose_lang: "Choose your preferred language",
        email_notif: "Email Notifications",
        email_notif_desc: "Get account updates via email",
        sms_alerts: "SMS Alerts",
        sms_alerts_desc: "Receive SMS for every transaction",
        push_notif: "Push Notifications",
        push_notif_desc: "Browser and app push alerts",
        trans_alerts: "Transaction Alerts",
        trans_alerts_desc: "Every debit and credit notification",
        offers_promo: "Offers & Promotions",
        offers_promo_desc: "Banking deals and offers",
        security_alerts: "Security Alerts",
        security_alerts_desc: "Login attempts & security warnings",
        recommended: "Recommended",
        important: "Important",
        critical: "Critical",
      },
      mr: {
        dashboard: "डॅशबोर्ड",
        my_profile: "माझी प्रोफाईल",
        open_account: "नवीन खाते उघडा",
        kyc_verification: "KYC पडताळणी",
        balance_check: "बॅलन्स चेक करा",
        transaction_history: "व्यवहार इतिहास",
        account_details: "खाते तपशील",
        help_support: "मदत आणि समर्थन",
        settings: "सेटिंग्ज",
        logout: "लॉगआउट",
        account_number: "खाते क्रमांक",
        account_holder: "खातेदाराचे नाव",
        account_type: "खात्याचा प्रकार",
        select_account_type: "खात्याचा प्रकार निवडा",
        saving_account: "बचत खाते (Saving)",
        current_account: "चालू खाते (Current)",
        check_balance_btn: "बॅलन्स तपासा",
        checking_btn: "तपासत आहे...",
        download_statement: "स्टेटमेंट PDF डाऊनलोड करा",
        profile: "प्रोफाईल",
        security: "सुरक्षा",
        preferences: "प्राधान्ये",
        language: "भाषा (Language)",
        english: "इंग्रजी (English)",
        marathi: "मराठी",
        money_transfer: "पैसे पाठवा (Transfer)",
        beneficiary_details: "लाभार्थी तपशील",
        acc_holder_name: "खातेदाराचे नाव",
        confirm_acc_number: "खाते क्रमांकाची पुष्टी करा",
        ifsc_code: "IFSC कोड",
        ifsc_note: "IFSC कोड बरोबर ११ अक्षरांचा असल्याची खात्री करा.",
        payment_details: "पेमेंट तपशील",
        amount_to_transfer: "पाठवायची रक्कम",
        remarks_optional: "शेरा (पर्यायी)",
        what_is_this_for: "हे कशासाठी आहे?",
        clear_details: "माहिती पुसा",
        transfer_securely: "सुरक्षितपणे पाठवा",
        processing: "प्रक्रिया सुरू आहे...",
        transfer_success: "व्यवहार यशस्वी!",
        transfer_success_msg: "तुमचे पैसे यशस्वीरीत्या लाभार्थीला पाठवले गेले आहेत.",
        secure_footer: "सर्व व्यवहार त्वरित केले जातात आणि २५६-बिट एन्क्रिप्शनद्वारे सुरक्षित आहेत.",
        submit_kyc: "नवीन KYC सबमिट करा",
        step_1: "पायरी १ — वैयक्तिक माहिती",
        step_2: "पायरी २ — कागदपत्रे",
        step_3: "पायरी ३ — OTP पडताळणी",
        personal: "वैयक्तिक",
        documents: "कागदपत्रे",
        otp: "OTP",
        full_name: "पूर्ण नाव",
        email: "ईमेल",
        phone: "फोन नंबर",
        dob: "जन्मतारीख",
        address: "पत्ता",
        next: "पुढे",
        aadhaar_number: "आधार क्रमांक",
        pan_number: "PAN क्रमांक",
        aadhaar_doc: "आधार कागदपत्र",
        pan_doc: "PAN कागदपत्र",
        upload_aadhaar: "आधार PDF किंवा फोटो अपलोड करा",
        upload_pan: "PAN PDF किंवा फोटो अपलोड करा",
        upload_limit: "PDF, JPG, PNG — जास्तीत जास्त 5MB",
        kyc_pending_note: "सबमिट केल्यानंतर, ॲडमिनने तपासणी करेपर्यंत तुमचे KYC 'प्रलंबित' (Pending) राहील.",
        back: "मागे",
        sending_otp: "OTP पाठवत आहे...",
        kyc_success: "KYC यशस्वीरित्या सबमिट झाले!",
        kyc_success_msg: "तुमचे KYC आता तपासणीसाठी प्रलंबित आहे. ॲडमिन लवकरच पडताळणी करतील.",
        enter_otp: "OTP प्रविष्ट करा",
        otp_placeholder: "६-अंकी OTP",
        otp_expiry: "OTP मुदत संपत आहे",
        resend_otp: "OTP पुन्हा पाठवा",
        submitting: "सबमिट करत आहे...",
        submit_kyc_btn: "KYC सबमिट करा",
        secure_portal: "सुरक्षित बँकिंग नोंदणी पोर्टल",
        personal_details: "वैयक्तिक तपशील",
        bank_holder_name: "पूर्ण नाव (खातेदार)",
        father_name: "वडिलांचे नाव",
        gender: "लिंग",
        select_gender: "लिंग निवडा",
        male: "पुरुष",
        female: "स्त्री",
        other: "इतर",
        contact_details: "संपर्क तपशील",
        residential_address: "राहण्याचा पत्ता",
        preferred_branch: "पसंतीची शाखा",
        purpose_of_opening: "खाते उघडण्याचे कारण",
        nominee_details: "वारसदार (Nominee) तपशील",
        nominee_name: "वारसदाराचे नाव",
        nominee_relation: "वारसदाराशी नाते",
        doc_upload: "कागदपत्रे अपलोड करा",
        passport_photo: "पासपोर्ट फोटो",
        clear_face_photo: "स्पष्ट चेहऱ्याचा फोटो",
        front_aadhaar: "आधार कार्डची पुढची बाजू",
        clear_pan_img: "PAN कार्डचा स्पष्ट फोटो",
        click_to_upload: "अपलोड करण्यासाठी क्लिक करा",
        terms_agree: "मी पुष्टी करतो की दिलेली सर्व माहिती अचूक आणि बरोबर आहे.",
        add_signature: "स्वाक्षरी जोडा",
        pending_approval: "मंजुरी प्रलंबित",
        submission_received: "माहिती प्राप्त झाली. ॲडमिन तपासणी सुरू आहे.",
        applicant: "अर्जदार",
        okay_understood: "ठीक आहे, समजले",
        profile_update_success: "प्रोफाईल यशस्वीरित्या अपडेट झाली ✅",
        error_occurred: "त्रुटी आली ❌",
        acc_no: "खाते क्र",
        acc_not_opened: "खाते: अद्याप उघडलेले नाही",
        save: "जतन करा",
        edit: "सुधारा",
        saving: "जतन करत आहे...",
        branch: "शाखा",
        ifsc: "IFSC कोड",
        placeholder_address: "तुमचा पत्ता प्रविष्ट करा...",
        address_not_added: "पत्ता अद्याप जोडलेला नाही - जोडण्यासाठी 'सुधारा' (Edit) वर क्लिक करा",
        acc_not_opened_msg: "बँक खाते अद्याप उघडलेले नाही. सेवा सुरू करण्यासाठी कृपया नवीन खाते उघडा.",
        create_acc_btn: "खाते तयार करा",
        secure_smart_banking: "सुरक्षित · स्मार्ट · बँकिंग",
        loading_acc_details: "खात्याचा तपशील लोड होत आहे...",
        official_record: "अधिकृत रेकॉर्ड",
        download_statement_btn: "स्टेटमेंट डाऊनलोड करा",
        no_acc_linked: "तुमच्या प्रोफाईलशी कोणतेही बँक खाते जोडलेले नाही.",
        open_new_acc_btn: "+ नवीन खाते उघडा",
        active: "सक्रिय (Active)",
        bank_name: "बँक",
        payzen_bank: "पेझेंन बँक (PayZen Bank)",
        personal_info: "वैयक्तिक माहिती",
        contact_info: "संपर्क माहिती",
        kyc_info: "KYC माहिती",
        nominee_info: "वारसदार (Nominee) माहिती",
        kyc_verified: "KYC पडताळणी पूर्ण",
        registered_address: "नोंदणीकृत पत्ता",
        disclaimer_mask: "तुमच्या सुरक्षिततेसाठी आधार आणि पॅन नंबर यांसारखी संवेदनशील माहिती अंशतः लपविली आहे. पूर्ण तपशीलासाठी, वैध ओळख पुराव्यासह तुमच्या जवळच्या PayZen बँकेच्या शाखेला भेट द्या.",
        copied: "कॉपी केले",
        copy: "कॉपी करा",
        acc_info: "खाते माहिती",
        notifications: "सूचना (Notifications)",
        manage_account_pref: "तुमच्या खात्याची प्राधान्ये व्यवस्थापित करा",
        edit_profile: "प्रोफाईल सुधारा",
        update_profile_info: "तुमची प्रोफाईल माहिती अपडेट करा",
        profile_info: "प्रोफाईल माहिती",
        edit_profile_details: "तुमची प्रोफाईल माहिती सुधारा",
        data_encrypted_secure: "तुमचा डेटा कूटबद्ध (Encrypted) आणि सुरक्षित आहे.",
        cancel: "रद्द करा",
        saved: "जतन केले",
        save_changes: "बदल जतन करा",
        security_settings: "सुरक्षा सेटिंग्ज",
        manage_acc_protection: "तुमच्या खात्याच्या सुरक्षेचे व्यवस्थापन करा",
        change_password: "पासवर्ड बदला",
        update_pwd_regularly: "तुमचा लॉगिन पासवर्ड नियमितपणे अपडेट करा",
        change: "बदला",
        current_pwd: "चालू पासवर्ड",
        new_pwd: "नवीन पासवर्ड",
        confirm_pwd: "पासवर्डची पुष्टी करा",
        updating: "अपडेट होत आहे...",
        update_pwd_btn: "पासवर्ड अपडेट करा",
        recent_activity: "अलीकडील क्रियाकलाप",
        success_login: "यशस्वी लॉगिन",
        failed_login: "अयशस्वी लॉगिन",
        no_recent_activity: "कोणताही अलीकडील क्रियाकलाप आढळला नाही.",
        notif_pref: "सूचना प्राधान्ये",
        control_alerts: "तुम्हाला कोणत्या सूचना मिळतील ते नियंत्रित करा",
        save_pref_btn: "प्राधान्ये जतन करा",
        manage_lang_pref: "ॲपची भाषा आणि इतर प्राधान्ये व्यवस्थापित करा",
        choose_lang: "तुमची पसंतीची भाषा निवडा",
        email_notif: "ईमेल सूचना",
        email_notif_desc: "ईमेलद्वारे खात्याचे अपडेट्स मिळवा",
        sms_alerts: "SMS अलर्ट",
        sms_alerts_desc: "प्रत्येक व्यवहारासाठी SMS मिळवा",
        push_notif: "पुश सूचना",
        push_notif_desc: "ब्राउझर आणि ॲप पुश अलर्ट",
        trans_alerts: "व्यवहार अलर्ट",
        trans_alerts_desc: "प्रत्येक डेबिट आणि क्रेडिटची सूचना",
        offers_promo: "ऑफर आणि प्रोमोशन्स",
        offers_promo_desc: "बँकिंग सौदे आणि ऑफर्स",
        security_alerts: "सुरक्षा अलर्ट",
        security_alerts_desc: "लॉगिन प्रयत्न आणि सुरक्षा चेतावणी",
        recommended: "शिफारस केलेले",
        important: "महत्वाचे",
        critical: "गंभीर",
      }
    };
    return translations[language]?.[key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, toggleLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};
